version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
    depends_on:
      - backend
    restart: unless-stopped
